name: Convert Clash Nodes

on:
  workflow_run:
    workflows: ["自动获取ss节点"]
    types:
      - completed
      
  schedule:
    - cron: '*/90 * * * *'
      
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip pyyaml

    - name: Run conversion script
      run: |
        python convert_clash.py

    - name: Commit REMOTE.conf
      uses: EndBug/add-and-commit@v9
      with:
        author_name: 'github-actions[bot]'
        author_email: 'github-actions[bot]@users.noreply.github.com'
        message: 'Add REMOTE.conf'
        add: './clash.yaml'

        path: clash.yaml
